apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coingro-controller-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "create", "delete", "watch", "update", "patch", "replace"]
