apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coingro-controller-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: coingro
roleRef:
  kind: ClusterRole
  name: coingro-controller-role
  apiGroup: rbac.authorization.k8s.io
