apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strategies-pvc
  namespace: coingro
spec:
  accessModes:
    - ReadOnlyMany
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: strategies-snapshot
  resources:
    requests:
      storage: 10Gi
