apiVersion: v1
kind: Pod
metadata:
  name: test-coingro
  namespace: coingro
spec:
  containers:
  - name: test-container
    command: ["sleep", "1000"]
    image: us-central1-docker.pkg.dev/coingora/coingro-images/coingro:1.0.12
    volumeMounts:
    - mountPath: /coingro/strategies
      name: strategies
      readOnly: true
    # - mountPath: /coingro/user_data
    #   name: user-data
    env:
    # - name: CG_CONTROLLER_APP_ENV
    #   value: kubernetes
    - name: COINGRO__INITIAL_STATE
      value: running
    - name: COINGRO__FORCE_ENTRY_ENABLE
      value: 'true'
    - name: COINGRO__DB_CONFIG__DRIVERNAME
      value: mysql
    - name: COINGRO__DB_CONFIG__USERNAME
      value: coingro_bot
    - name: COINGRO__DB_CONFIG__PASSWORD
      value: botpassword145
    - name: COINGRO__DB_CONFIG__HOST
      value: '64.225.29.241'
    - name: COINGRO__DB_CONFIG__PORT
      value: '3306'
    - name: COINGRO__DB_CONFIG__DATABASE
      value: coingro_bots
    - name: COINGRO__STRATEGY
      value: SampleStrategy
    - name: COINGRO__LOGFILE
      value: default
    - name: CG_BOT_ID
      value: SampleStrategy
    imagePullPolicy: Always
  volumes:
  - name: strategies
    persistentVolumeClaim:
      claimName: strategies-pvc
  # - name: user-data
  #   persistentVolumeClaim:
  #     claimName: user-data-pvc
  securityContext:
    fsGroup: 1000
    # runAsUser: 1000
