apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: strategies-snapshot
  namespace: coingro
spec:
  volumeSnapshotClassName: coingro-snapshotclass
  source:
    persistentVolumeClaimName: strategies-pvc-src